<?xml version="1.0" encoding="utf-8"?><Database Name="u0187499_dbOrg" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=wpl12.hosting.reg.ru;Initial Catalog=u0187499_dbOrg;Persist Security Info=True;User ID=u0187499_sberbank" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="sberbankQRConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.List$" Member="List_s">
    <Type Name="List_">
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BIC" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PersonalAcc" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeINN" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CorrespAcc" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="OrdNum" Type="System.Double" DbType="Float NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>